# This workflow must exist on the default branch to enable GitHub's Web UI and API
# to trigger workflow runs. The typical development process is to edit this file on
# a feature branch, then use the Web UI/API to target and test the branch version.
name: Minimal Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v4
      - name: Install minimal deps
        run: uv sync --extra dev
      - name: Run a quick pytest smoke
        run: |
          uv run pytest -rA --color=yes \
            tests/util \
            tests/dataset \
            tests/log \
            tests/scorer \
            tests/solver \
            tests/analysis \
            -k "not sandbox"
